### ISSUE TITLE
iOS Integration

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/vialer-middleware#2]
Hello Team,

Please provide me the example or documents of middleware for iOS Application. so i will refer it, and implementing in VialerSIPLib Example. Right now i am not receiving any incoming calls. Please help me ASAP. Thanking you.

**Comment by m-vellinga** [comment]
Hello mital87,

To be able to receive incoming calls using this (vialer-middleware) and the VialerSIPLib you must meet the following requirements:

* Have access to PBX software (like Asterisk) and be able to code dialplans for it;
* Have a machine to run this middleware;
* Have Apple Push Notification Service certificates/accounts;

It's nearly impossible to provide a solution that works out of the box. The steps provided in the readme labled as `Concept` should all be implemented (or in control of the developer using the VialerSIPLib) for it to work.

Also stated in the readme as `Final note`:
```
Although this is a fully functional product for us do not expect this to be the case for your situation. Our goal is to keep the source open so other developers can learn from our approach and adapt our code to their needs or start from scratch with the architecture and inner workings all planned out already.```

If you need any help we can point you in the right direction but a `clone and run` solution we can't provide due to the complex nature of all systems involved.

**Comment by bobvoorneveld** [comment]
If you would like to see how we integrated that part, please check:
https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/APNS/APNSHandler.m
https://github.com/VoIPGRID/vialer-ios/blob/develop/Vialer/Middleware/Middleware.m
