### ISSUE TITLE
Required Installation Steps

### ISSUE THREAD

**Issue by mital87** [VoIPGRID/vialer-middleware#3]
@m-vellinga: Please provide me the **steps** of **vialer middleware installation** on **the server**. so i will be followed that steps. Please help me ASAP. Thanking you.

**Comment by m-vellinga** [comment]
First you need to edit the code:

Remove api/auhtentication.py

Edit api/views.py
```python
from .authentication import VoipgridAuthentication  # delete this line
authentication_classes = (VoipgridAuthentication, )  # delete this line
```
NOTE: This breaks all security measures! You need to implement your own form of authentication if you care about security

With these code changes you can do (if you have docker/docker-compose)

```
$ docker-compose build
$ docker-compose up
```

You will now have running server with no data which you can access at localhost:8007

Create a superuser for the /admin interface:

```
$ docker-compose run app python manage.py createsuperuser
```

You can now access /admin and create apps that should be able to register.

For FCM put the token in the token field
For GCM put the filename of the push cert in the token field and put the certificate itself in deploy/local/

If you have setup your PBX to make an api call to incoming-call of this api you now should have a working DEVELOPMENT setup. I can not provide you with a production setup because this piece of software is not designed to be used by other people. It's merely open source so people can learn from it or make something that works for their situation.
